export const parents = [
    {
        fathers: ["Benjamin", "Daniel", "Joshua", "Noah", "Andrew", "Juan", "Alex", "Isaac", "Evan", "Ethan", "Vincent", "Angel", "Diego", "Adrian", "Gabriel", "Michael", "Santiago", "Kevin", "Louis", "Samuel", "Anthony", "Claude", "Niko", "John"],
        mothers: ["Hannah", "Aubrey", "Jasmine", "Gisele", "Amelia", "Isabella", "Zoe", "Ava", "Camila", "Violet", "Sophia", "Evelyn", "Nicole", "Ashley", "Gracie", "Brianna", "Natalie", "Olivia", "Elizabeth", "Charlotte", "Emma", "Misty"]
    }
]

export let skin = [
    // Player Appearance
    {
        name: 'Veidas',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'face', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Plaukai',
        id: 1,
        slider: true,
        description: 'Veikejo Plauku pasirinkimas',
        model: 'hair', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Plauku Atspalvis',
        id: 1,
        slider: true,
        description: 'Veikejo plauku atspalvio pasirinkimas',
        model: 'hair_shade', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Antakiai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'eyebrows', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Antakiu Aukstis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'eyebrown_high', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Antakiu Islindimas',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'eyebrown_forward', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Barzda',
        id: 1,
        slider: true,
        description: 'Veikejo barzdos pasirinkimas',
        model: 'beard', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Blush',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'blush', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Lupdazis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'lipstick', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Lupu Storumas',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'lips_thickness',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Zandai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'cheek_1', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Zandai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'cheek_2', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Zandai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'cheek_3', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Makiazas',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'makeup', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Makiazo Atspalvis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'makeup_shade', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Amzius',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'ageing', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Akiu Spalva',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'eye_color', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Akiu Tarpas',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'eye_opening', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Moles',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'moles', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Nosies Plotis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'nose_0', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Nosies Aukstis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'nose_1', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Nosis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'nose_2', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Nosis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'nose_3', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Nosis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'nose_4', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Nosis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'nose_5', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Zandikaulio Plotis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'jaw_bone_width', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Zandikaulio Ilgis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'jaw_bone_length', 
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Kaklo Storumas',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'neck_thickness',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    // Player Clothing
    {
        name: 'Maike',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 't-shirt',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Rankos',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'arms',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Dzemperis',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'torso2',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Kelnes',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'pants',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Batai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'shoes',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Liemene',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'vest',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Kauke',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'mask',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Aksesuarai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'accessory',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Kepures',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'hat',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Akiniai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'glass',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
    {
        name: 'Ausies Aksesuarai',
        id: 1,
        slider: true,
        description: 'Veikejo odos spalvos pasirinkimas',
        model: 'ear',
        mvalue:0, 
        tvalue:0, 
        max:50,
 tmax: 0,
    },
]